---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ dynatrace_hostname }}"
        dt_api_token: "{{ dynatrace_api_token }}"
        delay: 60 # Default is 60 seconds, i.e. the plugin polls problems every 60 seconds

  rules:
    - name: Problem payload Dynatrace for Website issues on Windows
      condition: event.title is match("Web Issue Windows")
      action:
        run_job_template:
          name: "Remediate Web Site Issue On Windows"
          organization: "Default"
